baseURL        : 'https://masputrawae.github.io/lumos_theme/'
languageCode   : 'id'
title          : 'My Garden'
enableEmoji    : true
enableGitInfo  : true

services:
  googleAnalytics:
    id: 'G-W9TMTZZYG5'

privacy:
  googleAnalytics:
    disable              : false
    respectDoNotTrack    : false

mediaType                : 'application/json'
outputFormats:
  search:
    mediaType            : 'application/json'
    baseName             : 'search'
    isPlainText          : true
    notAlternative       : true
  manifest:
    mediaType            : 'application/json'
    baseName             : 'manifest'
    isPlainText          : true
    notAlternative       : true
  sw:
    mediaType            : 'text/javascript'
    baseName             : 'sw'
    isPlainText          : true
    notAlternative       : true
  news:
    mediaType            : 'application/json'
    baseName             : 'news'
    isPlainText          : true
    notAlternative       : true
  offline:
    mediaType            : 'text/html'
    baseName             : 'offline'
    isPlainText          : true
    notAlternative       : true

outputs:
  home:
    - html
    - rss
    - sitemap
    - search
    - manifest
    - sw
    - news
    - offline

sitemap:
  filename  : 'sitemap.xml'
  priority  : 1.0
