baseURL       : 'https://masputrawae.github.io/READMEnya-ada-nanti/'
languageCode  : 'id'
title         : 'My Garden'
enableEmoji   : true

mediaType: "application/json"
outputFormats:
  search:
    mediaType: "application/json"
    baseName: "search"
    isPlainText: true
    notAlternative: true
  manifest:
    mediaType: "application/json"
    baseName: "manifest"
    isPlainText: true
    notAlternative: true
  sw:
    mediaType: "text/javascript"
    baseName: "sw"
    isPlainText: true
    notAlternative: true
  news:
    mediaType: "application/json"
    baseName: "news"
    isPlainText: true
    notAlternative: true
  offline:
    mediaType: "text/html"
    baseName: "offline"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["html", "rss", "sitemap", "search", "manifest", "sw", "news", "offline"]
