author      : 'Putra Jaya'
description : |
  In nostrud ut sunt cupidatat amet. Nostrud laboris occaecat qui sit adipisicing Lorem exercitation culpa sunt ut exercitation mollit. Deserunt sunt eu eiusmod amet dolore tempor do tempor culpa esse.
twitter     : '@Masputrawae'
emoji       : '🪴'
image       : assets/images/default-image.webp

showTaxonomies:
  - tags
  - categories

social:
  - name  : Facebook
    url   : https://facebook.com
    icon  : facebook

  - name  : Twitter X
    url   : https://x.com/
    icon  : twitter-x

  - name  : Discord
    url   : https://discord.com/
    icon  : discord

  - name  : GitHub
    url   : https://github.com/masputrawae/
    icon  : github

favicons:
  - rel   : icon
    type  : image/x-icon
    href  : assets/favicons/favicon.ico

  - rel   : apple-touch-icon
    type  : image/png
    size  : 180x180
    href  : assets/favicons/apple-touch-icon.png

  - rel   : icon
    type  : image/png
    size  : 32x32
    href  : assets/favicons/favicon-32x32.png

  - rel   : icon
    type  : image/png
    size  : 16x16
    href  : assets/favicons/favicon-16x16.png

  - rel   : icon
    type  : image/png
    size  : 192x192
    href  : assets/favicons/android-chrome-192x192.png

  - rel   : icon
    type  : image/png
    size  : 512x512
    href  : assets/favicons/android-chrome-512x512.png

# Copyright (optional, but it's good practice to keep it for attribution)
copyright: Theme by Putra Jaya