hugoVersion:
  extended        : true
  min             : '0.148.1'

mounts:
  - source        : 'content'
    target        : 'content'
    excludeFiles  : '99_templates/*'
  - source        : 'content'
    target        : 'content'
    excludeFiles  : '.obsidian/*'
  - source        : 'content'
    target        : 'content'
    excludeFiles  : '.trash/*'
  - source        : 'content'
    target        : 'content'
    excludeFiles  : 'private/*'